-- ------------------------------------------------------------ Ejercicios lecture 2
-- SELECT * FROM personas;
-- ------------------------------INNER JOIN
-- SELECT * FROM personas INNER JOIN ciudades
-- ON personas.ciudad = ciudades.id;
-- ------------------------------LEFT JOIN
-- SELECT * FROM personas LEFT JOIN ciudades
-- ON personas.ciudad = ciudades.id
-- WHERE ciudades.id IS NULL;
-- ------------------------------RIGHT JOIN
-- SELECT * FROM personas RIGHT JOIN ciudades
-- ON personas.ciudad = ciudades.id
-- WHERE personas.ciudad IS NULL;
-- ------------------------------------------------------------ Ejercicios Lecture 1
-- SELECT *
-- FROM personas
-- WHERE nombre ILIKE '%ba%';
-- SELECT AVG(rating)FROM personas;
-- SELECT * FROM personas WHERE rating > (SELECT AVG(rating)FROM personas);
-- SELECT * FROM ciudades;
-- CREATE TABLE personas
-- (
--     id SERIAL PRIMARY KEY,
--     apellido VARCHAR(255) NOT NULL,
--     nombre VARCHAR (255) UNIQUE,
--     rating INTEGER,
--     ciudad INTEGER REFERENCES ciudades (id)
-- );
-- SELECT * FROM personas;
-- INSERT INTO personas(apellido, nombre, rating, ciudad)
-- VALUES ('Smith', 'Morty', 7, 1),('Smith', 'Summer', 8, 2);
-- INSERT INTO personas(apellido, nombre, rating, ciudad)
-- VALUES ('Simpson', 'Bart', 8, 10);
-- SELECT * FROM personas WHERE rating = 7 AND nombre='Homero';
-- SELECT ciudad, SUM(rating) FROM personas GROUP BY ciudad;